---

name: Triage Tool Health Checks

run-name: Tests kicked off by ${{ github.actor }}
on:
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5
      - name: Lint
        run: uv run ruff check
      - name: Format
        run: uv run ruff format
